OvercastCommunity/PublicMaps

- ctw/standard/turf_wars/map.xml
The spawn drop protection extends down into the iron supply, which makes a large amount of iron unbreakable.
Also, the `spawn-drops` region is fully contained in the `bases` region, so only `bases` is needed.  Removing `spawn-drops` fixes the iron issue.
I also fixed my contributor UUID to my main account rather than my old alt.
> Turf Wars:  Fix unbreakable iron

- fun/arcade/red_agony/map.xml
Also fixes the (unused) closing </world-borders> tag, which was missing a letter
> Red Agony: Comment out unused World Border message

- fun/blitz/spaceship_battles_blitz/map.xml
On this map you will only lose lives after 5 minutes, so I think it makes sense for players to be able to join before Blitz starts
> Spaceship Battles Blitz: allow joining before 5 minutes

- flag/standard/hekla/map.xml
- flag/standard/promenade/map.xml
These maps have the KotF gamemode, but had the CTF tag, causing the wrong title to appear on scoreboard.
> Hekla & Promenade: Correct gamemode tags

- dtcm/standard/tatakai/map.xml
My localhost isn't working right now, so this change is untested. I'm not sure if it causes any unintentional side effects. Sorry!
Anyways, it should fix https://discord.com/channels/86514356862320640/172382420954251264/1110427638553649222 . Probably.
> Tatakai: Update void region rules

- koth/harvest/map.xml
In this latest change armour does not follow colour codes. This pull request is to change it so that the pink team is still wearing pink armour, not red.
> Harvest - change pink colour

- includes/kings-conquest.xml
This pull request makes significant changes to the King's Conquest gamemode.
- King damage has been redone to use the new damage actions. This means the king is no longer immune to all types of non-contact damage (e.g., fall).
- Maps can optionally include a race at the beginning of the match to decide who will be the king. There is a 30 second timelimit, and any undecided teams will have their king randomly chosen. The fallback behaviour is to pick a random king on match start if not used. This can be enabled by defining the following constants:
```xml
<constant id="king-race-start">x,y,z</constant>
<constant id="king-race-end">x,y,z</constant>
<constant id="king-race-start-yaw">yaw</constant>
```
- Added a world border which will appear at 7m30s and start shrinking  from 8m until the …
> Update King's Conquest gamemode include

- fun/arcade/ice_miners/map.xml
In the quiet part of the day this map gets picked regularly, but it will not start since not everyone will join and there are not enough players.
> Ice Miners: disable minimum players

- dtcm/black_gold/map.xml
- dtcm/blocks_dtc/map.xml
- dtcm/hot_dam_mini/map.xml
- dtcm/medieval_warfare/map.xml
- dtcm/nightsail/map.xml
- dtcm/precipice/map.xml
- dtcm/solitudemc/map.xml
- dtcm/spaceship_battles_ii/map.xml
- dtcm/swamped/map.xml
- dtcm/synergy/map.xml
- dtcm/temple_valley/map.xml
- dtcm/total_war/map.xml
- other/newstalgia/medieval_clayfare/map.xml
DTC maps made before proto 1.3.2 had two modes: gold block at 15 minutes and glass at 20 minutes. I've included the XML snippet below for more maps that may need it.
```xml
<modes>
<mode after="15m" material="gold block"/>
<mode after="20m" material="glass"/>
</modes>
```
Other than that, I've updated them for 1.5.0 standards. ~~I have not tested these maps, so I will do it as soon as possible.~~
> Restore core modes to DTC maps converted from proto <1.3.2

- ctf/directrix/map.xml
Currently the jump-pads on directrix and in the XML are listed to jump players downwards towards the enemies spawns like this:
https://github.com/user-attachments/assets/97559203-8571-4dee-bb86-eb234eabe8f9
_Note that there are already at least 2 faster ways to get to that jump-pad without using the rocket-ship route_
However when jumping onto the end of the pad it produces a totally different result:
https://github.com/user-attachments/assets/c72cca2e-c1f9-4308-8b7b-d3ab8f1ab8d2
(Both Examples from TTie)
This is due to the fact that when running/walking onto the jump-pad only the player bonks their head on the blocks behind which are pictured in this overhead screenshot instead of the player being launched upward as the velocity applied in XML is intended to do.
With these proposed …
> Fix Rocketship Reduxed Jumpads Regions for Directrix + Variants

- ffa/raid_ffa/map.xml
An oversight made in https://github.com/OvercastCommunity/PublicMaps/commit/25ffda9619e831906469970490dcfedb73c882cf caused the default rage variant to not grant arrows on kill. This PR fixes the issue and grants the arrows correctly.
> fix(raid_ffa): grant arrows on kill

- fun/blitz/winter_wars/map.xml
- Replaced Monument Modes with Fill Actions.
- Fixed an issue where the floor did not crumble successfully at the end of the match due to incorrect coordinates.
- Added an alert to warn players about the world border.
- Updated map version from 1.0.3 to 1.0.4.
> Winter Wars; Replace monument modes with fill actions

- other/payload/bardo/map.xml
I was testing the map and wanted to speed things up, so I temporarily set the payload capture time to 10 seconds, but then forgot to change it back after testing, lmao.
> Bardo; adjust payload capture time

- ctw/arabia/map.xml
- Simplified team ID references to utilize proto 1.5 improvements, eliminating redundant filter definitions.
- Added water bucket, wood:1 & wood:2 to itemkeep.
For some strange reason, birch planks (wood:2) don’t behave like other wood types. If you just specify `wood` in `itemkeep` or `itemremove`, birch will not be accounted for and will still drop on death, but every other type (oak, spruce, etc.) works fine. I've tested this on multiple maps, and still getting the same issue.
The fix for now is explicitly specifying `wood:2` in `itemkeep`, But someone should probably dig deeper, maybe this is an oversight on my part?
The changes above have also been tested on a private local testing server to ensure compatibility.
> Arabia; 1.3.3 - Fix very strange bug

- dtcm/tatakai/map.xml
- Added `<clear/>` on spawn-kit.
- Added unbreakable tag to tools.
- Switched damage resistance amplifier from 10 to 5 as the maximum effect potency for resistance is 5, anything beyond that won't have any extra effects.
- Removed carrot and disabled hunger, as it is disabled for most maps.
- Removed `wood`, `glass`, and `golden apple` from `itemremove` and added them to `itemkeep`.
> Tatakai: 1.0.5

- dtcm/palm_rust/map.xml
Over the years, this map has usually been rushed very quickly - by the time someone finishes crafting armor, the obsidian can already broken due to a 4 second break-time (3.5 seconds with enabled beacon). Majority of matches on this map are averaging somewhere around 6 mins.
I'd like to give it a shot to up the time to 5.8s by downgrading the efficiency - if this ends up backfiring, we can change it back. But measuring the blocks to distance in singleplayer, this change should be fine.
> Palm Rust: Change obsidian break time from 4.2s to 5.8s

- dtcm/loyalty_dtm/map.xml
- Added the `unbreakable` tag to all tools and armor.
- Replaced bread in the kit with a golden apple.
- Introduced golden apples kill reward using the appropriate include.
- Added golden apple, logs, and wood to `itemkeep`.
- Switched arrow from `itemremove` to `toolrepair` in case players drop/lose it by accident.
- Added flowers, and sugar cane to `itemremove`.
- Disabled hunger to follow standard map conventions.
> Loyalty dtm 1.1.5

- dtcm/grassy_mound/map.xml
- Replaced golden apple kill reward with gapple include.
- Swapped the golden carrot for a golden apple in the main kit and adjusted item slot positions accordingly.
- Reduced resistance amplifier in the kit from 10 to 5. (the max is 5)
- Simplified filters for better efficiency.
- Replaced build height regions with the `maxbuildheight` module (previous method was unnecessarily complex).
- Introduced `toolrepair` and `itemkeep`
- Added arrow, golden apple, wood, and stained clay to `itemkeep`
- Disabled hunger.
And as per usual, the changes above have been tested on a local PGM server to ensure compatibility.
> Grassy Mound: 1.0.2

- ctw/cargo/map.xml
- Renamed `red` and `blue` to `red-team` and `blue-team` respectively and updated all references accordingly.
- Simplified team ID references to utilize proto 1.5, eliminating redundant filter definitions.
- Simplified the spawn-kit item enchantments for better readability and maintainability.
- Cleaned up the chest filter to reduce unnecessary complexity.
- Removed the `block-drops` module entirely, as it caused blocks to not drop after breaking them, which can be quite annoying for anyone attempting to make a defense.
And as per usual, the changes above have been tested on a local PGM server to ensure compatibility.
> Cargo: 1.3.3

- includes/touchdown.xml
Pretty self explanatory this change is to ensure that stripping can only be triggered with melee kills instead of other damage sources such as projectiles.
This change was made in conjunction with the new map Prospect Park - https://github.com/OvercastCommunity/CommunityMaps/issues/1162
but applies to any future touchdown maps that may wish to use bows/crossbows
> Touchdown - Ensure only melee kills can strip the ball
